dependencies:
- name: exposecontroller
  version: 2.3.58
  repository: https://chartmuseum.build.cd.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.58
  repository: https://chartmuseum.build.cd.jenkins-x.io
  alias: cleanup
- name: mariadb
  version: 4.4.2
  repository: https://kubernetes-charts.storage.googleapis.com
  alias: database
- name: redis-ha
  version: 2.2.3
  repository: https://kubernetes-charts.storage.googleapis.com
  alias: redis
